# The town table

$Town = Array.new

$Town[0] = [ "Type",          "shop?", "%", "min", "Seniors", "Adults", "Young"]
$Town[1] = [ "Stronghold",          0,   1,     1,         3,        6,       4]
$Town[3] = [ "Inn",                 1,   2,     1,         2,        2,       2]
$Town[6] = [ "Farm",                1,   6,     3,         2,        2,       2]
$Town[4] = [ "General store",       1,   2,     1,         2,        2,       2]
$Town[7] = [ "Blacksmith",          1,   2,     1,         2,        2,       2]
$Town[2] = [ "Butcher",             1,   2,     1,         2,        2,       2]
$Town[6] = [ "Temple",              0,   5,     2,         2,        2,       2]
$Town[6] = [ "Mill",                0,   2,     0,         2,        2,       2]
$Town[6] = [ "Baker",               1,   2,     0,         2,        2,       2]
$Town[6] = [ "Merchant",            1,   3,     0,         2,        2,       2]
$Town[6] = [ "Tanner",              1,   3,     0,         2,        2,       2]
$Town[6] = [ "Doctor",              1,   2,     0,         2,        2,       2]
$Town[6] = [ "Grocery store",       1,   3,     0,         2,        2,       2]
$Town[8] = [ "Weapon smith",        1,   2,     0,         2,        2,       2]
$Town[6] = [ "Armourer",            1,   2,     0,         2,        2,       2]
$Town[5] = [ "Carpenter",           1,   3,     0,         2,        2,       2]
$Town[6] = [ "Worker",              0,   5,     0,         2,        2,       2]
$Town[6] = [ "Noble",               0,   3,     0,         2,        2,       2]
$Town[6] = [ "Slum",                0,   5,     0,         2,        2,       2]
$Town[6] = [ "Fletcher",            1,   2,     0,         2,        2,       2]
$Town[6] = [ "Jeweller",            1,   1,     0,         2,        2,       2]
$Town[6] = [ "Brothel",             1,   2,     0,         2,        2,       2]
$Town[6] = [ "Shoe maker",          1,   1,     0,         2,        2,       2]
$Town[6] = [ "Brewer",              1,   2,     0,         2,        2,       2]
$Town[6] = [ "Cobbler",             1,   2,     0,         2,        2,       2]
$Town[6] = [ "Builder",             0,   2,     0,         2,        2,       2]
$Town[6] = [ "Farm worker",         0,   2,     0,         2,        2,       2]
$Town[6] = [ "Artist",              1,   2,     0,         2,        2,       2]
$Town[6] = [ "Diplomat",            0,   2,     0,         2,        2,       2]
$Town[6] = [ "Silver/goldsmith",    1,   2,     0,         2,        2,       2]
$Town[6] = [ "Winery",              1,   2,     0,         2,        2,       2]
$Town[6] = [ "Destiller",           1,   2,     0,         2,        2,       2]
$Town[6] = [ "Teacher",             1,   6,     3,         2,        2,       2]
$Town[6] = [ "Scribe",              1,   6,     3,         2,        2,       2]
$Town[6] = [ "Cartographer",        1,   6,     3,         2,        2,       2]
$Town[6] = [ "Farm",                1,   6,     3,         2,        2,       2]
$Town[6] = [ "Farm",                1,   6,     3,         2,        2,       2]
$Town[6] = [ "Farm",                1,   6,     3,         2,        2,       2]
$Town[6] = [ "Farm",                1,   6,     3,         2,        2,       2]
$Town[6] = [ "Farm",                1,   6,     3,         2,        2,       2]
$Town[6] = [ "Farm",                1, 100,     3,         2,        2,       2]

