# Including all needed modules/functions from this one file

require_relative "d6s.rb"
require_relative "functions.rb"
require_relative "randomizer.rb"

require_relative "class_enc.rb"
require_relative "class_npc.rb"
require_relative "class_town.rb"
require_relative "class_npc_new.rb"
require_relative "class_enc_new.rb"
require_relative "class_monster_new.rb"
require_relative "town_relations.rb"
require_relative "weather.rb"
require_relative "weather2latex.rb"

require_relative "tables/armour.rb"
require_relative "tables/chartype.rb"
require_relative "tables/chartype_new.rb"
require_relative "tables/enc_specific.rb"
require_relative "tables/enc_type.rb"
require_relative "tables/encounters.rb"
require_relative "tables/magick.rb"
require_relative "tables/melee.rb"
require_relative "tables/missile.rb"
require_relative "tables/month.rb"
require_relative "tables/names.rb"
require_relative "tables/personality.rb"
require_relative "tables/town.rb"
require_relative "tables/weather.rb"
